# -*- coding: utf-8 -*-
"""Salary detector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S_y-UoySIq357lyHxwJrS3LLXoLR0VqB
"""

import numpy as np
import pandas as pd
dataset = pd.read_csv('Salary_Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2,random_state=0)

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

pred=regressor.predict([[float(input("Enter your Experience to know your salary in years\n"))]])
print(f"your Estimated salary will be {pred.item()}Rs"